"""
Author: Harshad Reddy Nalla

Fibonacci series is generated by notion each subsequent number is the sum of the previous two in list sequence.
Series: 0,1,1,2,3,5,8,....,N.
"""
def fab(number):
	x = 0
	y = 1
	if number < 0:
		print "Invalid Input"
	elif number == 0:
		print x
	elif number == 1:
		print x,"\n",y
	else:
		print x,"\n",y
		while number >= 2:
			z=x+y
			x=y
			y=z
			number=number-1
			print z



if __name__=="__main__":

	n=input("Enter the required number of Fibonacci sequence:")
	print "The Fibonacci series for the number is:"
	fab(n)